### ISSUE TITLE
Reversible drive controls

### ISSUE THREAD

**Issue by rtfoley** [frc5687/2016-Outlier2#6]
Acceptance
- Driver can switch end of the robot is considered "front" with a press of a button
- Button is used as a toggle, the new "front" will stay as the front until the button is pressed again
- Chosen button should not be easy to press accidentally

**Comment by BenBernardCIS** [comment]
As discussed today:
1. Direction will be a private int variable on OI, with 1 for forward and -1 for "reverse"
2. For now we wil uise the "back" button (Gamepad.Buttons.BACK) to trigger the switch.  We may want to require two buttons be pressed together to reduce accidental flips.
3. getRightSpeed and getLeftSpeed will "swap" inputs if direction is -1 (ie, getLeftSpeed will look at RIGHT_Y and getLeftSpeed will look at LEFT_Y)
4. Both will also multiply results by direction, so that when reversed the joystick range flips.
5. We may want to have a guard so that you can't "flip" if either joystick is outside the deadbands.

**Comment by BenBernardCIS** [comment]
@wilstenholme: @TheMightyWarPig may have already started on this--please coordinate with him.
